//
//  readme.h
//  sudoku
//
//  Created by Peng Wang on 11/21/15.
//  Copyright © 2015 Peng Wang. All rights reserved.
//

#ifndef readme_h
#define readme_h

// TODO: write a command line input init data.
/*
 g_pCubes[0][0]->SetValue(8);
 g_pCubes[0][1]->SetValue(0);
 g_pCubes[0][2]->SetValue(5);
 g_pCubes[0][3]->SetValue(0);
 g_pCubes[0][4]->SetValue(0);
 g_pCubes[0][5]->SetValue(1);
 g_pCubes[0][6]->SetValue(0);
 g_pCubes[0][7]->SetValue(0);
 g_pCubes[0][8]->SetValue(0);
 g_pCubes[1][0]->SetValue(0);
 g_pCubes[1][1]->SetValue(7);
 g_pCubes[1][2]->SetValue(0);
 g_pCubes[1][3]->SetValue(0);
 g_pCubes[1][4]->SetValue(8);
 g_pCubes[1][5]->SetValue(0);
 g_pCubes[1][6]->SetValue(0);
 g_pCubes[1][7]->SetValue(6);
 g_pCubes[1][8]->SetValue(0);
 g_pCubes[2][0]->SetValue(0);
 g_pCubes[2][1]->SetValue(3);
 g_pCubes[2][2]->SetValue(0);
 g_pCubes[2][3]->SetValue(0);
 g_pCubes[2][4]->SetValue(0);
 g_pCubes[2][5]->SetValue(0);
 g_pCubes[2][6]->SetValue(0);
 g_pCubes[2][7]->SetValue(0);
 g_pCubes[2][8]->SetValue(0);
 g_pCubes[3][0]->SetValue(6);
 g_pCubes[3][1]->SetValue(8);
 g_pCubes[3][2]->SetValue(0);
 g_pCubes[3][3]->SetValue(2);
 g_pCubes[3][4]->SetValue(0);
 g_pCubes[3][5]->SetValue(0);
 g_pCubes[3][6]->SetValue(0);
 g_pCubes[3][7]->SetValue(7);
 g_pCubes[3][8]->SetValue(0);
 g_pCubes[4][0]->SetValue(0);
 g_pCubes[4][1]->SetValue(0);
 g_pCubes[4][2]->SetValue(3);
 g_pCubes[4][3]->SetValue(0);
 g_pCubes[4][4]->SetValue(0);
 g_pCubes[4][5]->SetValue(0);
 g_pCubes[4][6]->SetValue(1);
 g_pCubes[4][7]->SetValue(0);
 g_pCubes[4][8]->SetValue(0);
 g_pCubes[5][0]->SetValue(0);
 g_pCubes[5][1]->SetValue(1);
 g_pCubes[5][2]->SetValue(0);
 g_pCubes[5][3]->SetValue(0);
 g_pCubes[5][4]->SetValue(0);
 g_pCubes[5][5]->SetValue(6);
 g_pCubes[5][6]->SetValue(0);
 g_pCubes[5][7]->SetValue(3);
 g_pCubes[5][8]->SetValue(4);
 g_pCubes[6][0]->SetValue(0);
 g_pCubes[6][1]->SetValue(0);
 g_pCubes[6][2]->SetValue(0);
 g_pCubes[6][3]->SetValue(0);
 g_pCubes[6][4]->SetValue(0);
 g_pCubes[6][5]->SetValue(0);
 g_pCubes[6][6]->SetValue(0);
 g_pCubes[6][7]->SetValue(8);
 g_pCubes[6][8]->SetValue(0);
 g_pCubes[7][0]->SetValue(0);
 g_pCubes[7][1]->SetValue(6);
 g_pCubes[7][2]->SetValue(0);
 g_pCubes[7][3]->SetValue(0);
 g_pCubes[7][4]->SetValue(7);
 g_pCubes[7][5]->SetValue(0);
 g_pCubes[7][6]->SetValue(0);
 g_pCubes[7][7]->SetValue(1);
 g_pCubes[7][8]->SetValue(0);
 g_pCubes[8][0]->SetValue(0);
 g_pCubes[8][1]->SetValue(0);
 g_pCubes[8][2]->SetValue(0);
 g_pCubes[8][3]->SetValue(3);
 g_pCubes[8][4]->SetValue(0);
 g_pCubes[8][5]->SetValue(0);
 g_pCubes[8][6]->SetValue(9);
 g_pCubes[8][7]->SetValue(0);
 g_pCubes[8][8]->SetValue(5);
 */

// Long Ranger
/*
 g_pCubes[0][0]->SetValue(2);
 g_pCubes[0][1]->SetValue(0);
 g_pCubes[0][2]->SetValue(0);
 g_pCubes[0][3]->SetValue(0);
 g_pCubes[0][4]->SetValue(0);
 g_pCubes[0][5]->SetValue(0);
 g_pCubes[0][6]->SetValue(0);
 g_pCubes[0][7]->SetValue(0);
 g_pCubes[0][8]->SetValue(8);
 g_pCubes[1][0]->SetValue(9);
 g_pCubes[1][1]->SetValue(0);
 g_pCubes[1][2]->SetValue(0);
 g_pCubes[1][3]->SetValue(0);
 g_pCubes[1][4]->SetValue(2);
 g_pCubes[1][5]->SetValue(8);
 g_pCubes[1][6]->SetValue(0);
 g_pCubes[1][7]->SetValue(5);
 g_pCubes[1][8]->SetValue(0);
 g_pCubes[2][0]->SetValue(0);
 g_pCubes[2][1]->SetValue(5);
 g_pCubes[2][2]->SetValue(6);
 g_pCubes[2][3]->SetValue(9);
 g_pCubes[2][4]->SetValue(4);
 g_pCubes[2][5]->SetValue(1);
 g_pCubes[2][6]->SetValue(0);
 g_pCubes[2][7]->SetValue(0);
 g_pCubes[2][8]->SetValue(0);
 g_pCubes[3][0]->SetValue(3);
 g_pCubes[3][1]->SetValue(8);
 g_pCubes[3][2]->SetValue(0);
 g_pCubes[3][3]->SetValue(0);
 g_pCubes[3][4]->SetValue(7);
 g_pCubes[3][5]->SetValue(0);
 g_pCubes[3][6]->SetValue(0);
 g_pCubes[3][7]->SetValue(0);
 g_pCubes[3][8]->SetValue(6);
 g_pCubes[4][0]->SetValue(6);
 g_pCubes[4][1]->SetValue(0);
 g_pCubes[4][2]->SetValue(4);
 g_pCubes[4][3]->SetValue(2);
 g_pCubes[4][4]->SetValue(0);
 g_pCubes[4][5]->SetValue(3);
 g_pCubes[4][6]->SetValue(5);
 g_pCubes[4][7]->SetValue(0);
 g_pCubes[4][8]->SetValue(0);
 g_pCubes[5][0]->SetValue(7);
 g_pCubes[5][1]->SetValue(0);
 g_pCubes[5][2]->SetValue(5);
 g_pCubes[5][3]->SetValue(0);
 g_pCubes[5][4]->SetValue(6);
 g_pCubes[5][5]->SetValue(0);
 g_pCubes[5][6]->SetValue(0);
 g_pCubes[5][7]->SetValue(0);
 g_pCubes[5][8]->SetValue(0);
 g_pCubes[6][0]->SetValue(5);
 g_pCubes[6][1]->SetValue(0);
 g_pCubes[6][2]->SetValue(8);
 g_pCubes[6][3]->SetValue(0);
 g_pCubes[6][4]->SetValue(0);
 g_pCubes[6][5]->SetValue(7);
 g_pCubes[6][6]->SetValue(0);
 g_pCubes[6][7]->SetValue(0);
 g_pCubes[6][8]->SetValue(4);
 g_pCubes[7][0]->SetValue(0);
 g_pCubes[7][1]->SetValue(0);
 g_pCubes[7][2]->SetValue(7);
 g_pCubes[7][3]->SetValue(4);
 g_pCubes[7][4]->SetValue(0);
 g_pCubes[7][5]->SetValue(2);
 g_pCubes[7][6]->SetValue(6);
 g_pCubes[7][7]->SetValue(8);
 g_pCubes[7][8]->SetValue(0);
 g_pCubes[8][0]->SetValue(4);
 g_pCubes[8][1]->SetValue(0);
 g_pCubes[8][2]->SetValue(9);
 g_pCubes[8][3]->SetValue(8);
 g_pCubes[8][4]->SetValue(5);
 g_pCubes[8][5]->SetValue(6);
 g_pCubes[8][6]->SetValue(7);
 g_pCubes[8][7]->SetValue(0);
 g_pCubes[8][8]->SetValue(0);
 */

#endif /* readme_h */
